# DISPLAY SETTINGS
BASE_FPS = 60
DISP_WID = 960
DISP_HEI = 540
DISP_TITLE = "TEMPEST RUN"

# FONT SETTINGS
TITLE_SIZE = 64
OPTION_SIZE = 36
INFO_SIZE = 24

# MUSIC & SOUND SETTINGS
ENABLE_MUSIC = True
ENABLE_SOUND_EFFECTS = True
MASTER_VOLUME = 1.0
MUSIC_VOLUME = 1.0
SOUND_EFFECTS_VOLUME = 0.2

# DEBUG STUFF
USE_NEON = True
TESTMODE = True
